### ISSUE TITLE
"the program contains a trojan"

### ISSUE THREAD

**Issue by Joe8000** [stripe/stripe-cli#482] opened 2020-07-12 16:10 UTC
possible false positive but windows defender picked up Trojan:Win32/Occamy.C41 in the stripe.exe

**Comment by spelunka** [comment] 2020-07-12 20:16
I'm seeing the same result on my windows machine too
![cli](https://user-images.githubusercontent.com/64932209/87255698-ee690600-c441-11ea-9566-c7d03327b505.png)

**Comment by auchenberg-stripe** [comment] 2020-07-14 04:04
This is duplicate of https://github.com/stripe/stripe-cli/issues/481. We've submitted the latest version of the CLI to Microsoft for analysis.

**Closed by auchenberg-stripe** 2020-07-14 04:04 UTC
