### ISSUE TITLE
CLI listen doesn't recieve/forward to resent events

### ISSUE THREAD

**Issue by ilyavas** [stripe/stripe-cli#448] opened 2020-05-14 13:51 UTC
### Issue
I'm not sure is it bug or expected behaviour, but when i click resend for particular event at the Dashboard, the CLI listener dosn't recieve this event or doesn't do `forwar to` for it.
It is so for both Succeeded and Failed events.
The mode is Test.
CLI listen is setup correctly because it recieve new happened events.

### Expected Behavior
CLI listen recieve resent event as well as new event.

### Steps to reproduce
Just start CLI listen and resend any event at Dashboard

### Environment
Windows

**Comment by last1here** [comment] 2020-06-04 23:38
To add to this, the cli resend command `stripe events resend evt_*` also doesnt resend the events to the cli listener. Running the command just results in the event printing to the terminal.

**Comment by richardm-stripe** [comment] 2020-06-22 15:31
Hi @ilyavas, thank you for the report. I don't it was ever a specific intention for `listen` to receive resent events, but we should either make this lack of behavior more explicit, or add support for it. I'm reclassifying as an enhancement.

**Comment by richardm-stripe** [comment] 2020-06-22 16:14
Mm, actually I am marking as a duplicate of https://github.com/stripe/stripe-cli/issues/313 and closing.

**Closed by richardm-stripe** 2020-06-22 16:14 UTC
Labels: duplicate
