### ISSUE TITLE
doesnt seem to listen to more than one event?

### ISSUE THREAD

**Issue by shez1983** [stripe/stripe-cli#220] opened 2019-10-06 08:33 UTC
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
When I try to do two actions on stripe (Cancel subscription and Reactivate it) - it feels like it only listens to ONE event?
<img width="677" alt="Screenshot 2019-10-06 at 9 29 25 AM" src="https://user-images.githubusercontent.com/3440597/66266351-dc579880-e81b-11e9-8bcf-88e6c224a1b7.png">

### Expected Behavior
I expect the second action to also generate a console line indicating it has recieved an event?

### Steps to reproduce
Start up the cli  stripe listen --forward-to https://localhost/stripe/webhook
Go to your stripe dashboard - 
Create a subscription Product and create it for a dummy customer if there isnt one to play around with
Go to that customer and try to cancel the subscription. 
You will see one output:
```2019-10-06 09:26:29  Received: ```

But now when you try to reactivate it. You will not see any output. 

Also note that quitting* and restarting and then if you reactivate you see an acknowledge message like above but if you do a second action it again doesnt acknowledge it

*which in itself is broken - i try to do control +C, it doesnt seem to work, so i end up doing ctrl +c, x, z and command +c,z,x etc 

I am also not sure if when it fwds the request it uses a GET or a POST? as even the one event it acknowledges my App doesnt seem to be responding?

### Environment
macOS

**Comment by tomer-stripe** [comment] 2019-10-06 23:42
Sorry about that, that definitely should not be happening. I'm having trouble reproducing that when I run it locally. When I tried to run through the steps you suggested I get:
```
2019-10-06 16:37:10  Received: product.created [evt_1FQjHmByst5pquEt5mLhA5bm]
2019-10-06 16:37:52  Received: plan.created [evt_1FQjIRByst5pquEtjOamYodo]
2019-10-06 16:38:36  Received: customer.updated [evt_1FQjJ9Byst5pquEtdF2v9w61]
2019-10-06 16:38:36  Received: payment_method.attached [evt_1FQjJ9Byst5pquEtuy84jsnr]
2019-10-06 16:38:36  Received: customer.source.created [evt_1FQjJAByst5pquEtCyFQkfy8]
2019-10-06 16:38:40  Received: payment_intent.created [evt_1FQjJDByst5pquEtjAPPTg3Y]
2019-10-06 16:38:40  Received: charge.succeeded [evt_1FQjJEByst5pquEtL3iaOwOK]
2019-10-06 16:38:40  Received: payment_intent.succeeded [evt_1FQjJEByst5pquEtI82bNMY3]
2019-10-06 16:38:40  Received: customer.updated [evt_1FQjJEByst5pquEtCHoLDin8]
2019-10-06 16:38:40  Received: invoice.created [evt_1FQjJEByst5pquEtpcLVP1AT]
2019-10-06 16:38:40  Received: invoice.finalized [evt_1FQjJEByst5pquEts3oxPMFp]
2019-10-06 16:38:40  Received: invoice.payment_succeeded [evt_1FQjJEByst5pquEtn6w4ToRD]
2019-10-06 16:38:41  Received: customer.subscription.created [evt_1FQjJEByst5pquEtUh8T4Ua1]
2019-10-06 16:39:02  Received: customer.subscription.deleted [evt_1FQjJaByst5pquEtuusLyN9h]
```

I'm also unable to reproduce the issue with with ctrl+c :(

What version of the CLI are you running? Is there any output after `Received: `? Like the type or the event id?

> I am also not sure if when it fwds the request it uses a GET or a POST? as even the one event it acknowledges my App doesnt seem to be responding?

The forwarding will POST to the url you provided (which is the same behavior from stripe.com)

**Comment by ob-stripe** [comment] 2019-10-23 00:57
Hi @shez1983. Are you still observing the issue? If so, can you try upgrading to the latest version of the Stripe CLI? We've made some changes that might help (in particular Ctrl+C should now work as expected).

**Comment by ob-stripe** [comment] 2019-11-06 22:09
Closing this, but feel free to reply if you're still observing this issue and we'll reopen.

**Closed by ob-stripe** 2019-11-06 22:09 UTC
Labels: bug
