### ISSUE TITLE
Trigger for connect account.updated event

### ISSUE THREAD

**Issue by khushwanth** [stripe/stripe-cli#546] opened 2020-11-25 04:52 UTC
### Problem
Using stripe CLI to trigger account.updated. However, there is no such trigger supported for now.

### Feature
Adding Trigger account.updated for connected accounts when the users log in through Express Dashboard and update verification documents or other information that are updatable.

**Comment by JamesTPF** [comment] 2020-12-24 09:55
Duplicate of https://github.com/stripe/stripe-cli/issues/345 with 29 up votes

**Comment by pepin-stripe** [comment] 2021-01-11 17:58
closed since duplicate of #345

**Closed by pepin-stripe** 2021-01-11 17:58 UTC
Labels: enhancement
