### ISSUE TITLE
Stripe CLI: Add account.updated event

### ISSUE THREAD

**Issue by ilken** [stripe/stripe-cli#407] opened 2020-03-26 14:00 UTC
### Problem
_What are you trying to do?_

As part of the Stripe Capabilities upgrade, we are testing the new ID verification but account.updated webhook is not listed on the supported events (https://github.com/stripe/stripe-cli/wiki/trigger-command#supported-events)

**Comment by jefcoserrca** [comment] 2020-07-16 02:22
did you resolve it?

**Comment by vahidvdn** [comment] 2020-09-28 14:33
+1

**Comment by JamesTPF** [comment] 2020-12-24 09:56
Duplicate of https://github.com/stripe/stripe-cli/issues/345

**Comment by pepin-stripe** [comment] 2021-01-11 17:58
closed since duplicate for #345

**Closed by pepin-stripe** 2021-01-11 17:58 UTC
Labels: enhancement, unsupported-event-type
