### ISSUE TITLE
Stripe - Virus Detected

### ISSUE THREAD

**Issue by CookieHax** [stripe/stripe-cli#894] opened 2022-06-13 21:45 UTC
On attempt to install
![image](https://user-images.githubusercontent.com/61884850/173450438-4f744642-da37-4981-8219-c83b4e59fd7f.png)

Reason: 
![image](https://user-images.githubusercontent.com/61884850/173450536-c86c0406-3fb4-4fde-b5f8-31e001c9e7bf.png)

Any ideas would be greatly appreciated! 

Thanks for any help,

**Comment by justinasmussen** [comment] 2022-06-15 09:08
I tried to download this using chrome and it will not download says "Failed - virus detected"

**Comment by clintonrocksmith** [comment] 2022-06-16 06:32
@suz-stripe This is an FYI for you about the VIRUS in the zip download for Stripe CLI

**Comment by clintonrocksmith** [comment] 2022-06-16 06:37
A workaround is to install the previous version:  1.10.2
https://github.com/stripe/stripe-cli/releases

**Comment by clintonrocksmith** [comment] 2022-06-17 00:18
Further investigation on Windows.  The x86-x64 file now no longer reports a virus, which has changed from yesterday.  However the xi386 file does now report a virus.  Nothing new has been updated and the only thing I can think of is the location where these zip files are stored has something altering them at random (COMPLETE SPECULATION).

I would recommend trying to download all the files daily to see which ones report a virus.  I'll do this myself over the next few days.

![image](https://user-images.githubusercontent.com/140419/174198224-ad95b746-6940-4e74-afe2-528364e5328f.png)

**Comment by charliecruzan-stripe** [comment] 2022-06-17 12:55
thanks @clintonrocksmith for investigating this more! But I'm going to close this issue since it's a duplicate of https://github.com/stripe/stripe-cli/issues/692, and keep the discussion there in one place

**Closed by charliecruzan-stripe** 2022-06-17 12:55 UTC
Labels: bug
