### ISSUE TITLE
Flag events emitted by stripe-cli to avoid environment conflicts

### ISSUE THREAD

**Issue by Freezystem** [stripe/stripe-cli#319] opened 2019-11-22 17:06 UTC
### Problem
Hi, we are trying to distinguish requests emitted by `stripe-cli` from request emitted by our staging environment. 

As our staging environment and CI are using the same webhooks broadcaster (test mode), events emitted by the `stripe-cli` in our CI are also reaching our staging environment.

Our event has metadata that are scoped to the environment, so when a `stripe-cli` request lends on our staging, hooks are returning 404 errors making stripe panicking and sending us alarming emails and finally, deactivating our staging webhook.

### Feature
It could be great to add a flag in the event object to be able to know if the `stripe-cli` is the emitter of the event so other environments will be able to ignore these requests.

Regards,

**Comment by tomer-stripe** [comment] 2019-12-02 21:45
Thanks for the suggestion @Freezystem! Will look into this.

**Comment by ob-stripe** [comment] 2019-12-10 00:00
I think it's unlikely we'd change the shape of the event object itself to flag it as being caused by the CLI.

For events caused by the `trigger` command specifically, we can try to tag the API resources themselves. I've started doing this in #334: for resources that have a `description` field, we will now fill the field with `(created by the Stripe CLI)`. We could also do something similar with metadata for resources that support it (most of them).

More generally though, if you want to avoid confusion between events, I would recommend using entirely separate Stripe accounts. You can create as many test accounts as you need, and you can configure the CLI to be used with different accounts using the `--project-name` flag.

Closing for now, but feel free to reply!

**Closed by ob-stripe** 2019-12-10 00:00 UTC
Labels: enhancement

**Comment by Freezystem** [comment] 2019-12-10 14:09
Thanks a lot, this will sure help us a lot. 
I wasn't aware that several test accounts were possible. We'll try that first.
Regards

**Comment by boycce** [comment] 2020-11-05 21:05
Local and staging development environments are very common and crucial to stable development. Setting up extra Stripe accounts is cumbersome due to progressive inconsistencies.
