### ISSUE TITLE
Add support for payout webhooks

### ISSUE THREAD

**Issue by dnsbty** [stripe/stripe-cli#365] opened 2020-02-06 21:23 UTC
### Problem
I'm testing some functionality around payouts within my application. Currently I'm having to use ngrok with my dev environment to make that work.

### Feature
Ideally I would be able to trigger payout webhooks from within the CLI. These include

- payout.cancelled
- payout.created
- payout.failed
- payout.paid
- payout.updated

For me, `payout.paid` and `payout.failed` will be the two most important ones to have, but it would be nice if all of them were supported.

### Examples
I would like to be able to call
```
stripe trigger payout.failed
```
or
```
stripe trigger payout.paid
```
and receive a webhook with the appropriate information

**Comment by tomer-stripe** [comment] 2020-02-20 01:39
Hey @dnsbty! Looks like this is a dupe of #330. I'm going to close this in favor of that one (since there are more people watching that issue for now). Could you subscribe to that one for updates?

**Closed by tomer-stripe** 2020-02-20 01:39 UTC
Labels: enhancement
