### ISSUE TITLE
Unable to run on 32-bit Windows

### ISSUE THREAD

**Issue by victor-sarabia** [stripe/stripe-cli#464] opened 2020-06-13 06:41 UTC
I downloaded and extracted the file stripe_1.4.1_windows_x86_64.zip

Then, I tried to run the stripe.exe file

But I got a message saying "The version of this file is not compatible with the version of Windows you are running ..."

Running on 32-bit Windows 7

**Comment by richardm-stripe** [comment] 2020-06-15 17:33
Hello @victor-sarabia, thanks for opening an issue. We have not historically supported or provided binaries for 32-bit windows, so I am reclassifying this as a feature request.

There seem to be others https://github.com/stripe/stripe-cli/issues/463 https://github.com/stripe/stripe-cli/issues/460 recently reporting this for the first time, so I am curious: was 32-bit Windows previously able to run the 64-bit binary somehow in previous versions? Is this your first time attempting to run the Stripe CLI?

**Comment by richardm-stripe** [comment] 2020-06-15 17:35
Closing as duplicate of #463

**Closed** 2020-06-15 17:35 UTC
Labels: bug
