### ISSUE TITLE
trigger subscription_schedule.created fails with "parameter_unknown"

### ISSUE THREAD

**Issue by opfertunes-anl** [stripe/stripe-cli#554] opened 2020-12-29 00:20 UTC
### Issue
stripe trigger subscription_schedule.created (or any other subscription_schedule.* event) fails with "parameter_unknown"

### Expected Behavior
The event triggers as expected

### Steps to reproduce

`$ stripe trigger subscription_schedule.created  `          

### Traceback
```
Setting up fixture for: customer
Setting up fixture for: plan
Setting up fixture for: subscription_schedule
Trigger failed: Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: phases[0][plans]",
    "param": "phases[0][plans]",
    "type": "invalid_request_error"
  }
}

Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: phases[0][plans]",
    "param": "phases[0][plans]",
    "type": "invalid_request_error"
  }
}
```

### Environment
macOS

Catalina: tried both the Brew install and downloading the latest binary directly.

**Comment by opfertunes-anl** [comment] 2020-12-29 00:31
Well turns out the events I **really** want are customer.subscription.* (which work fine)

But, this is an issue on my Catalina machine, FYI.

**Comment by pepin-stripe** [comment] 2021-01-11 17:50
@opfertunes-anl glad to hear at least you are unblocked with `customer.subscription.*`! 

I've tested `subscription_schedule.created` and indeed it fails for me too. I've filed a task internally and we'll work on looking into what the issue is.

**Comment by JulianBissekkou** [comment] 2021-01-20 15:55
Is there an update on this issue?

**Comment by pepin-stripe** [comment] 2021-01-20 15:59
The task is in our backlog and we're hoping to get to it asap.

**Comment by rijkvanzanten** [comment] 2021-01-21 01:42
For what it's worth, I'm seeing the same issue when using `subscription_schedule.canceled`:

```
% stripe trigger subscription_schedule.canceled

Setting up fixture for: customer
Setting up fixture for: plan
Setting up fixture for: subscription_schedule
Trigger failed: Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: phases[0][plans]",
    "param": "phases[0][plans]",
    "type": "invalid_request_error"
  }
}

Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: phases[0][plans]",
    "param": "phases[0][plans]",
    "type": "invalid_request_error"
  }
}
```

**Comment by pepin-stripe** [comment] 2021-01-21 16:07
Thanks for reporting @rijkvanzanten. Seems like it might be the same issue.

We are planning on prioritizing that next sprint for our runner, so we are hoping to get this fixed soon!

**Comment by ctrudeau-stripe** [comment] 2021-01-22 22:44
https://github.com/stripe/stripe-cli/pull/579

These will work now in the latest version 1.5.8. I've fixed canceled which will be released with the next version.

**Closed by ctrudeau-stripe** 2021-01-22 22:44 UTC
Labels: bug, unsupported-event-type
