### ISSUE TITLE
`stripe listen` stuck `Getting ready...`

### ISSUE THREAD

**Issue by fishcharlie** [stripe/stripe-cli#997] opened 2022-11-09 02:12 UTC
### Issue

Running `stripe listen` is stuck on `Getting ready...`.

### Expected Behavior

It to actually connect and forward webhook messages.

### Steps to reproduce

1. Run `stripe listen --project-name myProject --forward-to localhost:3000/webhooks/stripe`

### Traceback

```
⢿ Getting ready...
```

### Environment

macOS 13.0 (22A380)

```
stripe -v
stripe version 1.13.0
```

**Comment by charliecruzan-stripe** [comment] 2022-11-09 23:11
hey @fishcharlie, could you append `--log-level=debug` to your `stripe listen` command and paste the output? It looks like stripe cli is having trouble establishing the connection

I would also check any firewall settings you might have

**Comment by fishcharlie** [comment] 2022-11-13 03:18
@charliecruzan-stripe This started occurring when updating the Stripe CLI. I haven't made any changes to any firewall or network settings recently.

```
[Sat, 12 Nov 2022 20:15:52 MST] DEBUG config.Config.InitConfig: Using profiles file path=/Users/charliefish/.config/stripe/config.toml
⣟ Checking for new versions...[Sat, 12 Nov 2022 20:15:55 MST] DEBUG Error while sending telemetry data: Post "https://r.stripe.com/0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[Sat, 12 Nov 2022 20:16:02 MST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣾ Getting ready...[Sat, 12 Nov 2022 20:16:13 MST] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe default_version=2020-08-27 display_connect_filter_warning=false latest_version=2022-08-01 reconnect_delay=246 websocket_authorized_feature=webhook-payloads websocket_id=cliws_{39296}_ZLBTosUc29bZwDOnB3nw0gTi2LAILSb9ghHqnYcO4jADE6xhRc websocket_url=wss://stripecli-ws-nw.stripe.com/subscribe/acct_1LO5u2DtglIdt4Zm
[Sat, 12 Nov 2022 20:16:13 MST] DEBUG websocket.client.Run: Attempting to connect to Stripe
[Sat, 12 Nov 2022 20:16:13 MST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripecli-ws-nw.stripe.com/subscribe/acct_1LO5u2DtglIdt4Zm?websocket_feature=webhook-payloads
⣯ Getting ready...[Sat, 12 Nov 2022 20:16:16 MST] DEBUG Error while sending telemetry data: Post "https://r.stripe.com/0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

⢿ Getting ready...[Sat, 12 Nov 2022 20:16:23 MST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: lookup stripecli-ws-nw.stripe.com: i/o timeout message=
[Sat, 12 Nov 2022 20:16:23 MST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⣯ Getting ready...[Sat, 12 Nov 2022 20:16:33 MST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripecli-ws-nw.stripe.com/subscribe/acct_1LO5u2DtglIdt4Zm?websocket_feature=webhook-payloads
⣽ Getting ready...[Sat, 12 Nov 2022 20:16:43 MST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: lookup stripecli-ws-nw.stripe.com: i/o timeout message=
[Sat, 12 Nov 2022 20:16:43 MST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⡿ Getting ready...[Sat, 12 Nov 2022 20:16:53 MST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripecli-ws-nw.stripe.com/subscribe/acct_1LO5u2DtglIdt4Zm?websocket_feature=webhook-payloads
⣷ Getting ready...[Sat, 12 Nov 2022 20:17:03 MST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: lookup stripecli-ws-nw.stripe.com: i/o timeout message=
[Sat, 12 Nov 2022 20:17:03 MST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⣻ Getting ready...[Sat, 12 Nov 2022 20:17:13 MST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripecli-ws-nw.stripe.com/subscribe/acct_1LO5u2DtglIdt4Zm?websocket_feature=webhook-payloads
⣟ Getting ready...[Sat, 12 Nov 2022 20:17:23 MST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: lookup stripecli-ws-nw.stripe.com: i/o timeout message=
[Sat, 12 Nov 2022 20:17:23 MST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⣾ Getting ready...[Sat, 12 Nov 2022 20:17:33 MST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripecli-ws-nw.stripe.com/subscribe/acct_1LO5u2DtglIdt4Zm?websocket_feature=webhook-payloads
⢿ Getting ready...[Sat, 12 Nov 2022 20:17:43 MST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: lookup stripecli-ws-nw.stripe.com: i/o timeout message=
[Sat, 12 Nov 2022 20:17:43 MST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⢿ Getting ready...
```

**Comment by fishcharlie** [comment] 2022-11-16 00:01
@charliecruzan-stripe I don't think it's up to me to decide when to close issues as duplicates. That is really your responsibility.

That being said, it's **highly** concerning that issue has been open since April and still isn't fixed. Not a good look... this is a **MAJOR** issue and should be prioritized as such.

As for which version this started breaking in, I'm really not sure. All I remember is I recently ran `brew upgrade stripe` and it broke the next time I used Stripe CLI after that.

**Comment by charliecruzan-stripe** [comment] 2022-11-16 18:41
Thanks, I just wanted to make sure that you didn't think there was something unique about the problem you're describing in this issue that is different to the other one in 851. If there isn't then I'll close this in favor of that one

This has been a difficult issue to pin down, as it seems to appear and disappear for folks when their network changes, making this hard to reproduce & fix on our end. One comment on the other issue seems to indicate that this was fixed after logging into a _verified_ stripe account. Curious to know if that works for you, or if you're already logged into a verified account?

**Closed by charliecruzan-stripe** 2022-11-16 18:41 UTC
Labels: bug
