### ISSUE TITLE
exec /bin/stripe: exec format error when running v1.13.0 in a docker container

### ISSUE THREAD

**Issue by occamssafetyrazor** [stripe/stripe-cli#993] opened 2022-10-24 00:15 UTC
### Issue
I'm trying to run the latest version v1.13.0 in a docker container:
`docker run --rm -it --name stripe_old stripe/stripe-cli:v1.13.0`
This returns "exec /bin/stripe: exec format error"

### Expected Behavior
The latest version to return function as it did when running a container with version v1.12.4:
`docker run --rm -it --name stripe_old stripe/stripe-cli:v1.12.4`
This does not return an error

### Steps to reproduce
Just run
`docker run --rm -it --name stripe_old stripe/stripe-cli:v1.13.0`

### Traceback
exec /bin/stripe: exec format error

### Environment
Ubuntu 22.04.1 LTS
Docker version 20.10.17

**Comment by tomer-stripe** [comment] 2022-10-31 18:39
Hi folks, we're trying to reproduce this but are having some trouble. Could you share:
* Stripe CLI version
* Ubuntu version
* Docker version
* CPU arch (Intel, ARM/M1, etc)

**Comment by occamssafetyrazor** [comment] 2022-10-31 18:48
Hi @tomer-stripe 

stripe-cli:v1.13.0
Ubuntu 22.04.1 LTS
Docker version 20.10.17
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by Moizsohail** [comment] 2022-11-01 12:05
Getting the same error

**Comment by dmwyatt** [comment] 2022-11-01 17:46
Getting this as well:

* latest stripe CLI version as of the time of this post (aka, not specifying version on `docker run` command)
* Ubuntu 20.04.4
* Docker version 20.10.17, build 100c701
* CPU info follows (this is on Digital Ocean server)

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : DO-Regular
stepping        : 2
microcode       : 0x1
cpu MHz         : 2199.996
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_stale_data
bogomips        : 4399.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

**Comment by luka-papez** [comment] 2022-11-02 13:06
Hi @tomer-stripe

stripe-cli:v1.13.0
Ubuntu 22.04.1 LTS
Docker version 20.10.17
AMD Ryzen 7 5700G (x64)

I inspected the `stripe` binary from the container and this is the output:
```
> file stripe-1.13.0
stripe: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=yhu91cAOwRFsNL_9kwq8/Jt121z2mc58KFIsrB2XF/BYpej-nRxRxvcJuhro54/1GXGG7wqUCvpVeUOco5n, stripped
```
Looks like for some reason the binary for ARM ended up in the docker image.

When I run the same command on v1.12.4 I get this
```
file stripe-1.12.4
container_stripe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6Z0e8aWjtreTlYTsoVk4/G3MZWI1qJV9zfusb-eA3/G-i6P8wyM5kyvkDfR_jR/X4JsSI8YzM-_ztcuVK6k, stripped
```

**Comment by gracegoo** [comment] 2022-11-11 21:46
I see the same thing as well for 1.13.0 but for some reason I'm able to run the binary:

```
gracegoo@DESKTOP-51B2HQ8:~$ stripe --version
stripe version 1.13.0
gracegoo@DESKTOP-51B2HQ8:~$ docker run --rm -it --name stripe_old stripe/stripe-cli
The official command-line tool to interact with Stripe.

Before using the CLI, you'll need to login:

  $ stripe login
```

```
/ # file /bin/stripe
/bin/stripe: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=yhu91cAOwRFsNL_9kwq8/Jt121z2mc58KFIsrB2XF/BYpej-nRxRxvcJuhro54/1GXGG7wqUCvpVeUOco5n, stripped
```

stripe-cli:v1.13.0
Ubuntu 22.04.1 LTS
Docker version 20.10.20
CPU: x86_64 Intel

**Comment by gracegoo-stripe** [comment] 2022-11-11 22:55
Thanks all for reporting the issue! We will roll a release out on Monday.

**Comment by gracegoo-stripe** [comment] 2022-11-15 00:09
Okay, this should be fixed now with the last couple of PRs. 

Please run ` docker pull stripe/stripe-cli` to get the latest image. This will pull the correct version of the image based on what architecture the machine is running on. 
The version of the stripe CLI you're looking for is > 1.13.3.

**Comment by gracegoo-stripe** [comment] 2022-11-15 22:10
We got some reports that the latest image is not working for M1. Looking into that.
Meanwhile if you are on an M1 mac and don't need the latest stripe version, this should unblock you for now:
```
docker run --rm --it stripe/stripe-cli:v1.13.0
```

**Comment by gracegoo-stripe** [comment] 2022-11-21 21:48
New version out that should work for both platforms now: 
```
docker run stripe/stripe-cli version
stripe version 1.13.5
```

**Closed by gracegoo-stripe** 2022-11-21 21:48 UTC
Labels: bug
